config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :clients
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_user!
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :find_client, only: [:show, :edit, :update, :destroy]

  def index
    @q = Client.ransack(params[:q])
    @clients = @q.result.order(:name).page params[:page]
    @countclients = @q.result.count()
  end

  def show
  end

  def new
    @client = Client.new
  end

  def create
    @client = Client.new(client_params)
    if @client.save
      redirect_to @client
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @client.update(client_params)
      redirect_to @client
    else
      render :edit
    end
  end

  def destroy
    @client.destroy
    redirect_to clients_path
  end

  private

  def client_params
    params.require(:client).permit(:name, :firstname, :address, :streetnumber, :route, :zipcode, :city, :sublocality, :state, :country, :countryshort, :latitude, :longitude, :email)
  end

  def find_client
    @client = Client.find(params[:id])
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @countclients =  Client.count()
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/edit.html.erb
<div class="container-fluid padding-25 sm-padding-10">

  <div class="row">

    <div class="col-md-6 m-b-10">

      <div class="widget-13 panel no-border  no-margin widget-loader-circle">

        <div class="container-sm-height no-overflow">
          <div class="row row-sm-height">

            <%= simple_form_for @client do |f| %>
              <%= f.input :name %>
              <%= f.input :firstname %>
              <%= f.input :address %>
              <%= f.button :submit, "Ajouter", class: "btn btn-primary" %>

            <% end %>

          </div>
        </div>
      </div>

    </div>

    <div class="col-md-6 col-xlg-4">

    </div>

  </div>

</div>

app/views/clients/index.html.erb
<!-- START JUMBOTRON -->
<div class="jumbotron" data-pages="parallax">
  <div class="container-fluid container-fixed-lg sm-p-l-20 sm-p-r-20">
    <div class="row">
      <div class="col-md-12">
        <div class="panel-body">
          <%= link_to(new_client_path, class: "btn btn-success btn-cons", type: "button") do %>
            <i class="fa fa-user-plus"></i> <span class="bold">Nouveau</span>
          <% end %>
          </a>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- END JUMBOTRON -->
<div class="container-fluid sm-padding-10">
  <div class="row">
    <div class="col-md-12">
      <div class="container-fixed-lg bg-white">
        <div class="panel">
          <div class="panel-heading">
            <div class="panel-title">Liste des Clients (<%= @countclients %>)
            </div>
            <div class="pull-right">
              <div class="col-xs-12">
                <%= search_form_for @q do |f| %>
                  <%= f.search_field :name_or_firstname_cont, class: "form-control", placeholder: "Recherche" %>
                <% end %>
              </div>
            </div>
            <div class="clearfix">
            </div>
          </div>
          <div class="panel-body">
            <div id="tableWithExportOptions_wrapper" class="dataTables_wrapper form-inline no-footer">
              <div class="table-responsive">
                <table class="table table-striped dataTable no-footer" id="tableWithExportOptions" role="grid" aria-describedby="tableWithExportOptions_info">
                  <thead>
                    <tr>
                      <th><%= sort_link(@q, :name, 'Nom', default_order: :desc) %></th>
                      <th><%= sort_link(@q, :firstname, 'Prénom') %></th>
                      <th><%= sort_link(@q, :zipcode, 'Code Postal') %></th>
                      <th><%= sort_link(@q, :city, 'Ville') %></th>
                      <th><%= sort_link(@q, :email, 'Email') %></th>
                      <th>Visualiser</th>
                    </tr>
                  </thead>
                  <tbody>
                    <% @clients.each do |client| %>
                      <tr>
                        <td><%= client.name %></td>
                        <td><%= client.firstname %></td>
                        <td><%= client.zipcode %></td>
                        <td><%= client.city %></td>
                        <td><%= client.email %></td>
                        <td>
                          <%= link_to(client_path(client.id), class: "btn btn-warning btn-cons", type: "button") do %>
                            <i class="fa fa-eye"></i> <span class="bold">Voir</span>
                          <% end %>
                        </td>
                      </tr>
                    <% end %>
                  </tbody>
                </table>
              </div>
              <div class="row">
                <%= paginate @clients %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/clients/new.html.erb
<div class="container-fluid padding-25 sm-padding-10">

  <div class="row">

    <div class="col-md-6">

      <div class="panel panel-default">

        <div class="panel-body">

          <h5>Nouveau Client</h5>

          <%= simple_form_for @client do |f| %>

            <div class="geo">

              <div class="form-group form-group-default required ">
                <%= f.label :firstname, 'Prénom' %>
                <%= f.text_field :firstname, class:"form-control" %>
              </div>

              <div class="form-group form-group-default required ">
                <%= f.label :name, 'Nom' %>
                <%= f.text_field :name, class:"form-control" %>
              </div>

              <div class="form-group form-group-default required ">
                <%= f.label :address, 'Adresse' %>
                <%= f.text_field :address, class:"form-control", id: "geocomplete" %>
              </div>

              <div class="form-group form-group-default required ">
                <%= f.label :email, 'Email' %>
                <%= f.text_field :email, class:"form-control", id: "geocomplete" %>
              </div>

              <%= f.input :streetnumber, :as => :hidden, input_html: { data: { geo: "street_number" } }  %>
              <%= f.input :route, :as => :hidden, input_html: { data: { geo: "route" } }  %>
              <%= f.input :zipcode, :as => :hidden, input_html: { data: { geo: "postal_code" } }  %>
              <%= f.input :city, :as => :hidden, input_html: { data: { geo: "locality" } }  %>
              <%= f.input :sublocality, :as => :hidden, input_html: { data: { geo: "sublocality" } }  %>
              <%= f.input :state, :as => :hidden, input_html: { data: { geo: "state" } }  %>
              <%= f.input :address, :as => :hidden, input_html: { data: { geo: "formatted_address" } }  %>
              <%= f.input :country, :as => :hidden, input_html: { data: { geo: "country" } }  %>
              <%= f.input :countryshort, :as => :hidden, input_html: { data: { geo: "country_short" } }  %>
              <%= f.input :latitude, :as => :hidden, input_html: { data: { geo: "lat" } }  %>
              <%= f.input :longitude, :as => :hidden, input_html: { data: { geo: "lng" } }  %>
              <%= f.button :submit, "Créer", class: "btn btn-success pull-right" %>

            </div>

          <% end %>

        </div>

      </div>

    </div>

    <div class="col-md-6">
    </div>

  </div>

</div>

<% content_for :scripts do %>
  <script>
    $("#geocomplete").geocomplete({ details: ".geo", detailsAttribute: "data-geo" });
  </script>
<% end %>

app/views/clients/show.html.erb
<!-- START JUMBOTRON -->
<div class="jumbotron" data-pages="parallax">
  <div class="container-fluid container-fixed-lg sm-p-l-20 sm-p-r-20">
    <div class="row">
      <div class="col-md-12">
        <div class="panel-body">
          <%= link_to(edit_client_path(@client), class: "btn btn-primary btn-cons", type: "button") do %>
            <i class="fa fa-pencil"></i> <span class="bold">Modifier</span>
          <% end %>
          <%= link_to(client_path(@client), method: :delete, class: "btn btn-danger btn-cons", type: "button") do %>
            <i class="fa fa-trash"></i> <span class="bold">Supprimer</span>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- END JUMBOTRON -->

<div class="container-fluid padding-25 sm-padding-10">

  <div class="row">

    <div class="col-md-6 m-b-10">

      <div class="widget-13 panel no-border  no-margin widget-loader-circle">

        <div class="container-sm-height no-overflow">
          <div class="row row-sm-height">
            <div class="col-sm-6 col-lg-6 col-xlg-6 col-sm-height col-top no-padding">
              <div class="panel-heading ">
                <div class="panel-title">Informations Client</div>
              </div>
              <div class="panel-body">
                <p class="hint-text all-caps font-montserrat small no-margin ">Client</p>
                <p class="all-caps font-montserrat  no-margin text-success "><%= @client.firstname + " " + @client.name %></p>
                <p class="all-caps font-montserrat  no-margin text-success "><%= @client.streetnumber %>, <%= @client.route %></p>
                <p class="all-caps font-montserrat  no-margin text-success "><%= @client.zipcode %> <%= @client.city %></p>
                <p class="all-caps font-montserrat  no-margin text-success "><%= @client.state %><%= @client.country %></p>
                <br>
                <p class="hint-text all-caps font-montserrat small no-margin ">Coordonnées</p>
                <p class="all-caps font-montserrat  no-margin text-warning "><%= @client.email %></p>
                <p class="all-caps font-montserrat  no-margin text-warning ">Téléphone 1</p>
                <p class="all-caps font-montserrat  no-margin text-warning ">Téléphone 2</p>
                <br>
                <p class="hint-text all-caps font-montserrat small no-margin ">Informations complémentaires</p>
                <p class="all-caps font-montserrat  no-margin text-success ">Date de naissance</p>
                <p class="all-caps font-montserrat  no-margin text-success ">Date de mariage</p>
              </div>
            </div>
            <div class="col-sm-6 col-lg-6 col-xlg-6 col-sm-height col-top no-padding relative">
                <div id="map" style='width: 100%; height: 400px;'></div>
            </div>
          </div>
        </div>
      </div>

    </div>

    <div class="col-md-6 col-xlg-4">

    </div>

  </div>

</div>

<% content_for :scripts do %>
  <script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
  <script type="text/javascript">
    var mapStyle = [{"featureType":"administrative.locality","elementType":"all","stylers":[{"hue":"#2c2e33"},{"saturation":7},{"lightness":19},{"visibility":"on"}]},{"featureType":"landscape","elementType":"all","stylers":[{"hue":"#ffffff"},{"saturation":-100},{"lightness":100},{"visibility":"simplified"}]},{"featureType":"poi","elementType":"all","stylers":[{"hue":"#ffffff"},{"saturation":-100},{"lightness":100},{"visibility":"off"}]},{"featureType":"road","elementType":"geometry","stylers":[{"hue":"#bbc0c4"},{"saturation":-93},{"lightness":31},{"visibility":"simplified"}]},{"featureType":"road","elementType":"labels","stylers":[{"hue":"#bbc0c4"},{"saturation":-93},{"lightness":31},{"visibility":"on"}]},{"featureType":"road.arterial","elementType":"labels","stylers":[{"hue":"#bbc0c4"},{"saturation":-93},{"lightness":-2},{"visibility":"simplified"}]},{"featureType":"road.local","elementType":"geometry","stylers":[{"hue":"#e9ebed"},{"saturation":-90},{"lightness":-8},{"visibility":"simplified"}]},{"featureType":"transit","elementType":"all","stylers":[{"hue":"#e9ebed"},{"saturation":10},{"lightness":69},{"visibility":"on"}]},{"featureType":"water","elementType":"all","stylers":[{"hue":"#e9ebed"},{"saturation":-78},{"lightness":67},{"visibility":"simplified"}]}];
    var handler = Gmaps.build('Google');
    handler.buildMap({
        internal: {id: 'map'},
        provider: {
          disableDefaultUI: true,
          zoom:      13,
          center:    new google.maps.LatLng(<%= @client.latitude %>,<%= @client.longitude %>),
          mapTypeId: google.maps.MapTypeId.ROADMAP,
          styles:    mapStyle,
          picture: {
      url: "https://addons.cdn.mozilla.net/img/uploads/addon_icons/13/13028-64.png",
      width:  36,
      height: 36
    }
        }
      },
      function(){
        markers = handler.addMarkers([
  {
    lat: <%= @client.latitude %>,
    lng: <%= @client.longitude %>,
    infowindow: "hello!"
  }
  ]);
      }
    );

  </script>
<% end %>

app/views/layouts/application.html.erb
<head>
  <meta http-equiv="content-type" content="text/html;charset=UTF-8" />
  <meta charset="utf-8" />
  <title>Rails Boiler Plate</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
  <link rel="apple-touch-icon" href="<%= image_path('ico/60.png') %>">
  <link rel="apple-touch-icon" sizes="76x76" href="<%= image_path('ico/76.png') %>">
  <link rel="apple-touch-icon" sizes="120x120" href="<%= image_path('ico/120.png') %>">
  <link rel="apple-touch-icon" sizes="152x152" href="<%= image_path('ico/152.png') %>">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-touch-fullscreen" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="default">
  <meta content="" name="description" />
  <meta content="" name="author" />

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>

  <!--[if lte IE 9]>
  <link href="/pages/css/ie9.css?v=pages-v1.0.0" rel="stylesheet" type="text/css" />
  <![endif]-->

  <script type="text/javascript">
    window.onload = function() {
      // fix for windows 8
      if (navigator.appVersion.indexOf("Windows NT 6.2") != -1)
        document.head.innerHTML += '<link rel="stylesheet" type="text/css" href="/pages/css/windows.chrome.fix.css?v=pages-v1.0.0" />'
    }
  </script>

  <%= csrf_meta_tags %>

  <%= yield :head %>

</head>

  <body class="fixed-header">

    <%= render 'shared/sidebar' %>

    <div class="page-container">

      <%= render 'shared/header' %>

      <div class="page-content-wrapper">

        <div class="content">
          <%= yield %>
        </div>

        <%= render 'shared/footer' %>

      </div>

    </div>

    <script src="//maps.google.com/maps/api/js?v=3&key=AIzaSyALZ4qUpLmReM7jwuaBSK6J0uPCOyKrrPQ&libraries=places"></script>
    <!-- JS at bottom of page to improve load time, and only loaded once with 'data-turbolinks-eval' == false  -->
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true, 'data-turbolinks-eval' => false %>

    <%= yield :scripts %>

  </body>

</html>

app/views/layouts/login.html.erb
<head>
  <meta http-equiv="content-type" content="text/html;charset=UTF-8" />
  <meta charset="utf-8" />
  <title>Rails Boiler Plate</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
  <link rel="apple-touch-icon" href="<%= image_path('ico/60.png') %>">
  <link rel="apple-touch-icon" sizes="76x76" href="<%= image_path('ico/76.png') %>">
  <link rel="apple-touch-icon" sizes="120x120" href="<%= image_path('ico/120.png') %>">
  <link rel="apple-touch-icon" sizes="152x152" href="<%= image_path('ico/152.png') %>">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-touch-fullscreen" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="default">
  <meta content="" name="description" />
  <meta content="" name="author" />

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>

  <!--[if lte IE 9]>
  <link href="/pages/css/ie9.css?v=pages-v1.0.0" rel="stylesheet" type="text/css" />
  <![endif]-->

  <script type="text/javascript">
    window.onload = function() {
      // fix for windows 8
      if (navigator.appVersion.indexOf("Windows NT 6.2") != -1)
        document.head.innerHTML += '<link rel="stylesheet" type="text/css" href="/pages/css/windows.chrome.fix.css?v=pages-v1.0.0" />'
    }
  </script>

  <%= csrf_meta_tags %>

  <%= yield :head %>
</head>

  <body class="fixed-header">

    <div class="login-wrapper">

      <%= yield %>

    </div>

    <!-- JS at bottom of page to improve load time, and only loaded once with 'data-turbolinks-eval' == false  -->
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true, 'data-turbolinks-eval' => false %>

  </body>

</html>

app/views/pages/home.html.erb
<!-- START CONTAINER FLUID -->
<div class="container-fluid padding-25 sm-padding-10">
  <!-- START ROW -->
  <div class="row">
    <div class="col-md-6 col-xlg-4">
      <div class="row">
        <div class="col-sm-6 m-b-10">
          <%= link_to(clients_path) do %>
            <div class="ar-1-1">
              <!-- START WIDGET widget_imageWidgetBasic-->
              <div class="widget-client panel no-border bg-primary widget no-margin">
                <div class="panel-body">
                  <div class="pull-bottom bottom-left bottom-right padding-25">
                    <span class="label font-montserrat fs-11"><%= @countclients %> CLIENTS</span>
                    <br>
                    <h3 class="text-white">Gestion Clients</h3>
                    <p class="text-white hint-text hidden-md">Création, modification...</p>
                  </div>
                </div>
              </div>
              <!-- END WIDGET -->
            </div>
          <% end %>
        </div>
        <div class="col-sm-6 m-b-10">
          <%= link_to(root_path) do %>
            <div class="ar-1-1">
              <!-- START WIDGET widget_imageWidgetBasic-->
                <div class="widget-emailing panel no-border bg-warning widget no-margin">
                  <div class="panel-body">
                    <div class="pull-bottom bottom-left bottom-right padding-25">
                      <span class="label font-montserrat fs-11">COMING SOON</span>
                      <br>
                      <h3 class="text-white">Campagne Emailing</h3>
                      <p class="text-white hint-text hidden-md">Ciblage, création, diffusion...</p>
                    </div>
                  </div>
                </div>
                <!-- END WIDGET -->
            </div>
          <% end %>
        </div>
      </div>
      <div class="row">
        <div class="col-sm-6 m-b-10">
          <%= link_to("http://www.poiray.com") do %>
            <div class="ar-1-1">
              <!-- START WIDGET widget_imageWidgetBasic-->
                <div class="widget-clientwebsite panel no-border bg-complete widget no-margin">
                  <div class="panel-body">
                    <div class="pull-bottom bottom-left bottom-right padding-25">
                      <span class="label font-montserrat fs-11">LIEN</span>
                      <br>
                      <h3 class="text-white">Mon site Internet</h3>
                      <p class="text-white hint-text hidden-md">Accéder à votre site...</p>
                    </div>
                  </div>
                </div>
                <!-- END WIDGET -->
            </div>
          <% end %>
        </div>
        <div class="col-sm-6 m-b-10">

        </div>
      </div>
    </div>
    <div class="col-md-6 col-xlg-4">
      <div class="row">
        <div class="col-sm-6 m-b-10">
          <%= mail_to("contact@evolutouch.com") do %>
            <div class="ar-1-1">
              <!-- START WIDGET widget_imageWidgetBasic-->
              <div class="widget-robot panel no-border bg-danger widget no-margin">
                <div class="panel-body">
                  <div class="pull-bottom bottom-left bottom-right padding-25">
                    <span class="label font-montserrat fs-11">COMING SOON</span>
                    <br>
                    <h3 class="text-white">Modules à venir !</h3>
                    <p class="text-white hint-text hidden-md">Participer à l'optimisation d'EvoluTouch.</p>
                  </div>
                </div>
              </div>
              <!-- END WIDGET -->
            </div>
          <% end %>
        </div>
        <div class="col-sm-6 m-b-10">

        </div>
      </div>
      <div class="row">
        <div class="col-sm-6 m-b-10">

        </div>
        <div class="col-sm-6 m-b-10">

        </div>
      </div>
    </div>
  </div>
  <!-- END ROW -->
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
<div class="alert alert-info" role="alert">
  <button class="close" data-dismiss="alert"></button>
  <%= alert %>
</div>
<% end %>

<% if alert %>
<div class="alert alert-danger" role="alert">
  <button class="close" data-dismiss="alert"></button>
  <%= alert %>
</div>
<% end %>

app/views/shared/_footer.html.erb
<!-- START FOOTER -->
<div class="container-fluid container-fixed-lg footer">
  <div class="copyright sm-text-center">
    <p class="small no-margin pull-left sm-pull-reset">
    </p>
    <p class="small no-margin pull-right sm-pull-reset">
      <span class="hint-text">Copyright © 2016</span>
      <span class="font-montserrat">EvoluTouch</span>.
      <span class="hint-text">All rights reserved.</span>
    </p>
    <div class="clearfix"></div>
  </div>
</div>
<!-- END FOOTER -->

app/views/shared/_header.html.erb
<div class="header ">
  <!-- START MOBILE CONTROLS -->
  <!-- LEFT SIDE -->
  <div class="pull-left full-height visible-sm visible-xs">
    <!-- START ACTION BAR -->
    <div class="sm-action-bar">
      <a href="#" class="btn-link toggle-sidebar" data-toggle="sidebar">
        <span class="icon-set menu-hambuger"></span>
      </a>
    </div>
    <!-- END ACTION BAR -->
  </div>
  <!-- RIGHT SIDE -->
  <!-- END MOBILE CONTROLS -->
  <div class=" pull-left sm-table">
    <div class="header-inner">
      <div class="brand inline">
        <img src="<%= image_path('logo.png') %>" alt="logo" data-src="<%= image_path('logo.png') %>" data-src-retina="<%= image_path('logo_2x.png') %>" width="150" height="20">
      </div>
    </div>
  </div>

  <div class=" pull-right">
    <!-- START User Info-->
    <div class="visible-lg visible-md m-t-10">
      <div class="pull-left p-r-10 p-t-10 fs-16 font-heading">
        <span class="semi-bold"><%= current_user.firstname + " " + current_user.name %></span>
      </div>
      <div class="dropdown pull-right">
        <button class="profile-dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <span class="thumbnail-wrapper d32 circular inline m-t-5">
          <img src="<%= image_path('profiles/avatar.jpg') %>" alt="" data-src="<%= image_path('profiles/avatar.jpg') %>" data-src-retina="<%= image_path('profiles/avatar_small2x.jpg') %>" width="32" height="32">
      </span>
        </button>
        <ul class="dropdown-menu profile-dropdown" role="menu">
          <li><a href="#"><i class="pg-settings_small"></i> Settings</a>
          </li>
          <!--
          <li><a href="#"><i class="pg-signals"></i> Help</a>
          </li>
          -->
          <li class="bg-master-lighter">
            <%= link_to(destroy_user_session_path, method: :delete, class: "clearfix") do %>
              <span class="pull-left">Logout</span>
              <span class="pull-right"><i class="pg-power"></i></span>
            <% end %>
          </li>
        </ul>
      </div>
    </div>
    <!-- END User Info-->
  </div>
</div>

app/views/shared/_sidebar.html.erb
<div class="page-sidebar" data-pages="sidebar">

  <div id="appMenu" class="sidebar-overlay-slide from-top">
  </div>

  <div class="sidebar-header">
    <img src="<%= image_path('logo_white.png') %>" alt="logo" class="brand" data-src="<%= image_path('logo_white.png') %>" data-src-retina="<%= image_path('logo_white_2x.png') %>" width="120" height="16">
    <div class="sidebar-header-controls">
      <button data-pages-toggle="#appMenu" class="btn btn-xs sidebar-slide-toggle btn-link" type="button">
      </button>
      <button data-toggle-pin="sidebar" class="btn btn-link visible-lg-inline" type="button"><i class="fa fs-12"></i>
      </button>
    </div>
  </div>

  <div class="sidebar-menu">
    <ul class="menu-items">

      <li class="m-t-30">
        <a href="<%= root_path %>">
          <span class="title">Accueil</span>
        </a>
        <span class="icon-thumbnail "><i class="pg-home"></i></span>
      </li>

      <li class="">
        <a href="<%= clients_path %>">
          <span class="title">Clients</span>
        </a>
        <span class="icon-thumbnail "><i class="pg-unordered_list"></i></span>
      </li>

      <li class="">
        <a href="<%= root_path %>">
          <span class="title">Emailing</span>
        </a>
        <span class="icon-thumbnail"><i class="pg-mail"></i></span>
      </li>

    </ul>
    <div class="clearfix"></div>

  </div>

</div>